# Generated by Django 4.2.6 on 2024-01-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0004_alter_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriberuser',
            old_name='subscribers',
            new_name='category',
        ),
    ]
